/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.alexkiyanov.iotplatform.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PoisonMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -590805938602083799L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PoisonMessage\",\"namespace\":\"com.github.alexkiyanov.iotplatform.avro\",\"fields\":[{\"name\":\"originalTopic\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"originalKey\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"originalValue\",\"type\":\"bytes\"},{\"name\":\"errorMessage\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"errorType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"retryAttempts\",\"type\":\"int\"},{\"name\":\"firstFailureTime\",\"type\":\"long\"},{\"name\":\"lastFailureTime\",\"type\":\"long\"},{\"name\":\"deviceId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"metadata\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PoisonMessage> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PoisonMessage> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PoisonMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PoisonMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PoisonMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PoisonMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PoisonMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PoisonMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PoisonMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String originalTopic;
  private java.lang.String originalKey;
  private java.nio.ByteBuffer originalValue;
  private java.lang.String errorMessage;
  private java.lang.String errorType;
  private int retryAttempts;
  private long firstFailureTime;
  private long lastFailureTime;
  private java.lang.String deviceId;
  private java.lang.String metadata;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PoisonMessage() {}

  /**
   * All-args constructor.
   * @param originalTopic The new value for originalTopic
   * @param originalKey The new value for originalKey
   * @param originalValue The new value for originalValue
   * @param errorMessage The new value for errorMessage
   * @param errorType The new value for errorType
   * @param retryAttempts The new value for retryAttempts
   * @param firstFailureTime The new value for firstFailureTime
   * @param lastFailureTime The new value for lastFailureTime
   * @param deviceId The new value for deviceId
   * @param metadata The new value for metadata
   */
  public PoisonMessage(java.lang.String originalTopic, java.lang.String originalKey, java.nio.ByteBuffer originalValue, java.lang.String errorMessage, java.lang.String errorType, java.lang.Integer retryAttempts, java.lang.Long firstFailureTime, java.lang.Long lastFailureTime, java.lang.String deviceId, java.lang.String metadata) {
    this.originalTopic = originalTopic;
    this.originalKey = originalKey;
    this.originalValue = originalValue;
    this.errorMessage = errorMessage;
    this.errorType = errorType;
    this.retryAttempts = retryAttempts;
    this.firstFailureTime = firstFailureTime;
    this.lastFailureTime = lastFailureTime;
    this.deviceId = deviceId;
    this.metadata = metadata;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return originalTopic;
    case 1: return originalKey;
    case 2: return originalValue;
    case 3: return errorMessage;
    case 4: return errorType;
    case 5: return retryAttempts;
    case 6: return firstFailureTime;
    case 7: return lastFailureTime;
    case 8: return deviceId;
    case 9: return metadata;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: originalTopic = value$ != null ? value$.toString() : null; break;
    case 1: originalKey = value$ != null ? value$.toString() : null; break;
    case 2: originalValue = (java.nio.ByteBuffer)value$; break;
    case 3: errorMessage = value$ != null ? value$.toString() : null; break;
    case 4: errorType = value$ != null ? value$.toString() : null; break;
    case 5: retryAttempts = (java.lang.Integer)value$; break;
    case 6: firstFailureTime = (java.lang.Long)value$; break;
    case 7: lastFailureTime = (java.lang.Long)value$; break;
    case 8: deviceId = value$ != null ? value$.toString() : null; break;
    case 9: metadata = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'originalTopic' field.
   * @return The value of the 'originalTopic' field.
   */
  public java.lang.String getOriginalTopic() {
    return originalTopic;
  }


  /**
   * Sets the value of the 'originalTopic' field.
   * @param value the value to set.
   */
  public void setOriginalTopic(java.lang.String value) {
    this.originalTopic = value;
  }

  /**
   * Gets the value of the 'originalKey' field.
   * @return The value of the 'originalKey' field.
   */
  public java.lang.String getOriginalKey() {
    return originalKey;
  }


  /**
   * Sets the value of the 'originalKey' field.
   * @param value the value to set.
   */
  public void setOriginalKey(java.lang.String value) {
    this.originalKey = value;
  }

  /**
   * Gets the value of the 'originalValue' field.
   * @return The value of the 'originalValue' field.
   */
  public java.nio.ByteBuffer getOriginalValue() {
    return originalValue;
  }


  /**
   * Sets the value of the 'originalValue' field.
   * @param value the value to set.
   */
  public void setOriginalValue(java.nio.ByteBuffer value) {
    this.originalValue = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.String getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.String value) {
    this.errorMessage = value;
  }

  /**
   * Gets the value of the 'errorType' field.
   * @return The value of the 'errorType' field.
   */
  public java.lang.String getErrorType() {
    return errorType;
  }


  /**
   * Sets the value of the 'errorType' field.
   * @param value the value to set.
   */
  public void setErrorType(java.lang.String value) {
    this.errorType = value;
  }

  /**
   * Gets the value of the 'retryAttempts' field.
   * @return The value of the 'retryAttempts' field.
   */
  public int getRetryAttempts() {
    return retryAttempts;
  }


  /**
   * Sets the value of the 'retryAttempts' field.
   * @param value the value to set.
   */
  public void setRetryAttempts(int value) {
    this.retryAttempts = value;
  }

  /**
   * Gets the value of the 'firstFailureTime' field.
   * @return The value of the 'firstFailureTime' field.
   */
  public long getFirstFailureTime() {
    return firstFailureTime;
  }


  /**
   * Sets the value of the 'firstFailureTime' field.
   * @param value the value to set.
   */
  public void setFirstFailureTime(long value) {
    this.firstFailureTime = value;
  }

  /**
   * Gets the value of the 'lastFailureTime' field.
   * @return The value of the 'lastFailureTime' field.
   */
  public long getLastFailureTime() {
    return lastFailureTime;
  }


  /**
   * Sets the value of the 'lastFailureTime' field.
   * @param value the value to set.
   */
  public void setLastFailureTime(long value) {
    this.lastFailureTime = value;
  }

  /**
   * Gets the value of the 'deviceId' field.
   * @return The value of the 'deviceId' field.
   */
  public java.lang.String getDeviceId() {
    return deviceId;
  }


  /**
   * Sets the value of the 'deviceId' field.
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.String value) {
    this.deviceId = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return The value of the 'metadata' field.
   */
  public java.lang.String getMetadata() {
    return metadata;
  }


  /**
   * Sets the value of the 'metadata' field.
   * @param value the value to set.
   */
  public void setMetadata(java.lang.String value) {
    this.metadata = value;
  }

  /**
   * Creates a new PoisonMessage RecordBuilder.
   * @return A new PoisonMessage RecordBuilder
   */
  public static com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder newBuilder() {
    return new com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder();
  }

  /**
   * Creates a new PoisonMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PoisonMessage RecordBuilder
   */
  public static com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder newBuilder(com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder other) {
    if (other == null) {
      return new com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder();
    } else {
      return new com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder(other);
    }
  }

  /**
   * Creates a new PoisonMessage RecordBuilder by copying an existing PoisonMessage instance.
   * @param other The existing instance to copy.
   * @return A new PoisonMessage RecordBuilder
   */
  public static com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder newBuilder(com.github.alexkiyanov.iotplatform.avro.PoisonMessage other) {
    if (other == null) {
      return new com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder();
    } else {
      return new com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for PoisonMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PoisonMessage>
    implements org.apache.avro.data.RecordBuilder<PoisonMessage> {

    private java.lang.String originalTopic;
    private java.lang.String originalKey;
    private java.nio.ByteBuffer originalValue;
    private java.lang.String errorMessage;
    private java.lang.String errorType;
    private int retryAttempts;
    private long firstFailureTime;
    private long lastFailureTime;
    private java.lang.String deviceId;
    private java.lang.String metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.originalTopic)) {
        this.originalTopic = data().deepCopy(fields()[0].schema(), other.originalTopic);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.originalKey)) {
        this.originalKey = data().deepCopy(fields()[1].schema(), other.originalKey);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.originalValue)) {
        this.originalValue = data().deepCopy(fields()[2].schema(), other.originalValue);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[3].schema(), other.errorMessage);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.errorType)) {
        this.errorType = data().deepCopy(fields()[4].schema(), other.errorType);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.retryAttempts)) {
        this.retryAttempts = data().deepCopy(fields()[5].schema(), other.retryAttempts);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.firstFailureTime)) {
        this.firstFailureTime = data().deepCopy(fields()[6].schema(), other.firstFailureTime);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.lastFailureTime)) {
        this.lastFailureTime = data().deepCopy(fields()[7].schema(), other.lastFailureTime);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.deviceId)) {
        this.deviceId = data().deepCopy(fields()[8].schema(), other.deviceId);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.metadata)) {
        this.metadata = data().deepCopy(fields()[9].schema(), other.metadata);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing PoisonMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.alexkiyanov.iotplatform.avro.PoisonMessage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.originalTopic)) {
        this.originalTopic = data().deepCopy(fields()[0].schema(), other.originalTopic);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.originalKey)) {
        this.originalKey = data().deepCopy(fields()[1].schema(), other.originalKey);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.originalValue)) {
        this.originalValue = data().deepCopy(fields()[2].schema(), other.originalValue);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[3].schema(), other.errorMessage);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.errorType)) {
        this.errorType = data().deepCopy(fields()[4].schema(), other.errorType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.retryAttempts)) {
        this.retryAttempts = data().deepCopy(fields()[5].schema(), other.retryAttempts);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.firstFailureTime)) {
        this.firstFailureTime = data().deepCopy(fields()[6].schema(), other.firstFailureTime);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lastFailureTime)) {
        this.lastFailureTime = data().deepCopy(fields()[7].schema(), other.lastFailureTime);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.deviceId)) {
        this.deviceId = data().deepCopy(fields()[8].schema(), other.deviceId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.metadata)) {
        this.metadata = data().deepCopy(fields()[9].schema(), other.metadata);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'originalTopic' field.
      * @return The value.
      */
    public java.lang.String getOriginalTopic() {
      return originalTopic;
    }


    /**
      * Sets the value of the 'originalTopic' field.
      * @param value The value of 'originalTopic'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setOriginalTopic(java.lang.String value) {
      validate(fields()[0], value);
      this.originalTopic = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'originalTopic' field has been set.
      * @return True if the 'originalTopic' field has been set, false otherwise.
      */
    public boolean hasOriginalTopic() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'originalTopic' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearOriginalTopic() {
      originalTopic = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'originalKey' field.
      * @return The value.
      */
    public java.lang.String getOriginalKey() {
      return originalKey;
    }


    /**
      * Sets the value of the 'originalKey' field.
      * @param value The value of 'originalKey'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setOriginalKey(java.lang.String value) {
      validate(fields()[1], value);
      this.originalKey = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'originalKey' field has been set.
      * @return True if the 'originalKey' field has been set, false otherwise.
      */
    public boolean hasOriginalKey() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'originalKey' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearOriginalKey() {
      originalKey = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'originalValue' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getOriginalValue() {
      return originalValue;
    }


    /**
      * Sets the value of the 'originalValue' field.
      * @param value The value of 'originalValue'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setOriginalValue(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.originalValue = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'originalValue' field has been set.
      * @return True if the 'originalValue' field has been set, false otherwise.
      */
    public boolean hasOriginalValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'originalValue' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearOriginalValue() {
      originalValue = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * @return The value.
      */
    public java.lang.String getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setErrorMessage(java.lang.String value) {
      validate(fields()[3], value);
      this.errorMessage = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorType' field.
      * @return The value.
      */
    public java.lang.String getErrorType() {
      return errorType;
    }


    /**
      * Sets the value of the 'errorType' field.
      * @param value The value of 'errorType'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setErrorType(java.lang.String value) {
      validate(fields()[4], value);
      this.errorType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'errorType' field has been set.
      * @return True if the 'errorType' field has been set, false otherwise.
      */
    public boolean hasErrorType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'errorType' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearErrorType() {
      errorType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'retryAttempts' field.
      * @return The value.
      */
    public int getRetryAttempts() {
      return retryAttempts;
    }


    /**
      * Sets the value of the 'retryAttempts' field.
      * @param value The value of 'retryAttempts'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setRetryAttempts(int value) {
      validate(fields()[5], value);
      this.retryAttempts = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'retryAttempts' field has been set.
      * @return True if the 'retryAttempts' field has been set, false otherwise.
      */
    public boolean hasRetryAttempts() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'retryAttempts' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearRetryAttempts() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstFailureTime' field.
      * @return The value.
      */
    public long getFirstFailureTime() {
      return firstFailureTime;
    }


    /**
      * Sets the value of the 'firstFailureTime' field.
      * @param value The value of 'firstFailureTime'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setFirstFailureTime(long value) {
      validate(fields()[6], value);
      this.firstFailureTime = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'firstFailureTime' field has been set.
      * @return True if the 'firstFailureTime' field has been set, false otherwise.
      */
    public boolean hasFirstFailureTime() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'firstFailureTime' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearFirstFailureTime() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastFailureTime' field.
      * @return The value.
      */
    public long getLastFailureTime() {
      return lastFailureTime;
    }


    /**
      * Sets the value of the 'lastFailureTime' field.
      * @param value The value of 'lastFailureTime'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setLastFailureTime(long value) {
      validate(fields()[7], value);
      this.lastFailureTime = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'lastFailureTime' field has been set.
      * @return True if the 'lastFailureTime' field has been set, false otherwise.
      */
    public boolean hasLastFailureTime() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'lastFailureTime' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearLastFailureTime() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviceId' field.
      * @return The value.
      */
    public java.lang.String getDeviceId() {
      return deviceId;
    }


    /**
      * Sets the value of the 'deviceId' field.
      * @param value The value of 'deviceId'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setDeviceId(java.lang.String value) {
      validate(fields()[8], value);
      this.deviceId = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceId' field has been set.
      * @return True if the 'deviceId' field has been set, false otherwise.
      */
    public boolean hasDeviceId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'deviceId' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearDeviceId() {
      deviceId = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * @return The value.
      */
    public java.lang.String getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder setMetadata(java.lang.String value) {
      validate(fields()[9], value);
      this.metadata = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'metadata' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.PoisonMessage.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PoisonMessage build() {
      try {
        PoisonMessage record = new PoisonMessage();
        record.originalTopic = fieldSetFlags()[0] ? this.originalTopic : (java.lang.String) defaultValue(fields()[0]);
        record.originalKey = fieldSetFlags()[1] ? this.originalKey : (java.lang.String) defaultValue(fields()[1]);
        record.originalValue = fieldSetFlags()[2] ? this.originalValue : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        record.errorMessage = fieldSetFlags()[3] ? this.errorMessage : (java.lang.String) defaultValue(fields()[3]);
        record.errorType = fieldSetFlags()[4] ? this.errorType : (java.lang.String) defaultValue(fields()[4]);
        record.retryAttempts = fieldSetFlags()[5] ? this.retryAttempts : (java.lang.Integer) defaultValue(fields()[5]);
        record.firstFailureTime = fieldSetFlags()[6] ? this.firstFailureTime : (java.lang.Long) defaultValue(fields()[6]);
        record.lastFailureTime = fieldSetFlags()[7] ? this.lastFailureTime : (java.lang.Long) defaultValue(fields()[7]);
        record.deviceId = fieldSetFlags()[8] ? this.deviceId : (java.lang.String) defaultValue(fields()[8]);
        record.metadata = fieldSetFlags()[9] ? this.metadata : (java.lang.String) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PoisonMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<PoisonMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PoisonMessage>
    READER$ = (org.apache.avro.io.DatumReader<PoisonMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.originalTopic);

    out.writeString(this.originalKey);

    out.writeBytes(this.originalValue);

    out.writeString(this.errorMessage);

    out.writeString(this.errorType);

    out.writeInt(this.retryAttempts);

    out.writeLong(this.firstFailureTime);

    out.writeLong(this.lastFailureTime);

    if (this.deviceId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.deviceId);
    }

    if (this.metadata == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.metadata);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.originalTopic = in.readString();

      this.originalKey = in.readString();

      this.originalValue = in.readBytes(this.originalValue);

      this.errorMessage = in.readString();

      this.errorType = in.readString();

      this.retryAttempts = in.readInt();

      this.firstFailureTime = in.readLong();

      this.lastFailureTime = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.deviceId = null;
      } else {
        this.deviceId = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.metadata = null;
      } else {
        this.metadata = in.readString();
      }

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.originalTopic = in.readString();
          break;

        case 1:
          this.originalKey = in.readString();
          break;

        case 2:
          this.originalValue = in.readBytes(this.originalValue);
          break;

        case 3:
          this.errorMessage = in.readString();
          break;

        case 4:
          this.errorType = in.readString();
          break;

        case 5:
          this.retryAttempts = in.readInt();
          break;

        case 6:
          this.firstFailureTime = in.readLong();
          break;

        case 7:
          this.lastFailureTime = in.readLong();
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.deviceId = null;
          } else {
            this.deviceId = in.readString();
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.metadata = null;
          } else {
            this.metadata = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










