/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.alexkiyanov.iotplatform.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeviceInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5041449856418445009L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeviceInfo\",\"namespace\":\"com.github.alexkiyanov.iotplatform.avro\",\"fields\":[{\"name\":\"deviceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"deviceType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"manufacturer\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"model\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"firmwareVersion\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"firstSeen\",\"type\":\"long\"},{\"name\":\"lastSeen\",\"type\":\"long\"},{\"name\":\"status\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeviceInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeviceInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeviceInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeviceInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeviceInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeviceInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeviceInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeviceInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeviceInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String deviceId;
  private java.lang.String deviceType;
  private java.lang.String manufacturer;
  private java.lang.String model;
  private java.lang.String firmwareVersion;
  private long firstSeen;
  private long lastSeen;
  private java.lang.String status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeviceInfo() {}

  /**
   * All-args constructor.
   * @param deviceId The new value for deviceId
   * @param deviceType The new value for deviceType
   * @param manufacturer The new value for manufacturer
   * @param model The new value for model
   * @param firmwareVersion The new value for firmwareVersion
   * @param firstSeen The new value for firstSeen
   * @param lastSeen The new value for lastSeen
   * @param status The new value for status
   */
  public DeviceInfo(java.lang.String deviceId, java.lang.String deviceType, java.lang.String manufacturer, java.lang.String model, java.lang.String firmwareVersion, java.lang.Long firstSeen, java.lang.Long lastSeen, java.lang.String status) {
    this.deviceId = deviceId;
    this.deviceType = deviceType;
    this.manufacturer = manufacturer;
    this.model = model;
    this.firmwareVersion = firmwareVersion;
    this.firstSeen = firstSeen;
    this.lastSeen = lastSeen;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deviceId;
    case 1: return deviceType;
    case 2: return manufacturer;
    case 3: return model;
    case 4: return firmwareVersion;
    case 5: return firstSeen;
    case 6: return lastSeen;
    case 7: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deviceId = value$ != null ? value$.toString() : null; break;
    case 1: deviceType = value$ != null ? value$.toString() : null; break;
    case 2: manufacturer = value$ != null ? value$.toString() : null; break;
    case 3: model = value$ != null ? value$.toString() : null; break;
    case 4: firmwareVersion = value$ != null ? value$.toString() : null; break;
    case 5: firstSeen = (java.lang.Long)value$; break;
    case 6: lastSeen = (java.lang.Long)value$; break;
    case 7: status = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'deviceId' field.
   * @return The value of the 'deviceId' field.
   */
  public java.lang.String getDeviceId() {
    return deviceId;
  }


  /**
   * Sets the value of the 'deviceId' field.
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.String value) {
    this.deviceId = value;
  }

  /**
   * Gets the value of the 'deviceType' field.
   * @return The value of the 'deviceType' field.
   */
  public java.lang.String getDeviceType() {
    return deviceType;
  }


  /**
   * Sets the value of the 'deviceType' field.
   * @param value the value to set.
   */
  public void setDeviceType(java.lang.String value) {
    this.deviceType = value;
  }

  /**
   * Gets the value of the 'manufacturer' field.
   * @return The value of the 'manufacturer' field.
   */
  public java.lang.String getManufacturer() {
    return manufacturer;
  }


  /**
   * Sets the value of the 'manufacturer' field.
   * @param value the value to set.
   */
  public void setManufacturer(java.lang.String value) {
    this.manufacturer = value;
  }

  /**
   * Gets the value of the 'model' field.
   * @return The value of the 'model' field.
   */
  public java.lang.String getModel() {
    return model;
  }


  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.String value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'firmwareVersion' field.
   * @return The value of the 'firmwareVersion' field.
   */
  public java.lang.String getFirmwareVersion() {
    return firmwareVersion;
  }


  /**
   * Sets the value of the 'firmwareVersion' field.
   * @param value the value to set.
   */
  public void setFirmwareVersion(java.lang.String value) {
    this.firmwareVersion = value;
  }

  /**
   * Gets the value of the 'firstSeen' field.
   * @return The value of the 'firstSeen' field.
   */
  public long getFirstSeen() {
    return firstSeen;
  }


  /**
   * Sets the value of the 'firstSeen' field.
   * @param value the value to set.
   */
  public void setFirstSeen(long value) {
    this.firstSeen = value;
  }

  /**
   * Gets the value of the 'lastSeen' field.
   * @return The value of the 'lastSeen' field.
   */
  public long getLastSeen() {
    return lastSeen;
  }


  /**
   * Sets the value of the 'lastSeen' field.
   * @param value the value to set.
   */
  public void setLastSeen(long value) {
    this.lastSeen = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.String getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.String value) {
    this.status = value;
  }

  /**
   * Creates a new DeviceInfo RecordBuilder.
   * @return A new DeviceInfo RecordBuilder
   */
  public static com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder newBuilder() {
    return new com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder();
  }

  /**
   * Creates a new DeviceInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeviceInfo RecordBuilder
   */
  public static com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder newBuilder(com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder other) {
    if (other == null) {
      return new com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder();
    } else {
      return new com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder(other);
    }
  }

  /**
   * Creates a new DeviceInfo RecordBuilder by copying an existing DeviceInfo instance.
   * @param other The existing instance to copy.
   * @return A new DeviceInfo RecordBuilder
   */
  public static com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder newBuilder(com.github.alexkiyanov.iotplatform.avro.DeviceInfo other) {
    if (other == null) {
      return new com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder();
    } else {
      return new com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeviceInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeviceInfo>
    implements org.apache.avro.data.RecordBuilder<DeviceInfo> {

    private java.lang.String deviceId;
    private java.lang.String deviceType;
    private java.lang.String manufacturer;
    private java.lang.String model;
    private java.lang.String firmwareVersion;
    private long firstSeen;
    private long lastSeen;
    private java.lang.String status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deviceId)) {
        this.deviceId = data().deepCopy(fields()[0].schema(), other.deviceId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.deviceType)) {
        this.deviceType = data().deepCopy(fields()[1].schema(), other.deviceType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.manufacturer)) {
        this.manufacturer = data().deepCopy(fields()[2].schema(), other.manufacturer);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.model)) {
        this.model = data().deepCopy(fields()[3].schema(), other.model);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.firmwareVersion)) {
        this.firmwareVersion = data().deepCopy(fields()[4].schema(), other.firmwareVersion);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.firstSeen)) {
        this.firstSeen = data().deepCopy(fields()[5].schema(), other.firstSeen);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.lastSeen)) {
        this.lastSeen = data().deepCopy(fields()[6].schema(), other.lastSeen);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.status)) {
        this.status = data().deepCopy(fields()[7].schema(), other.status);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing DeviceInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.alexkiyanov.iotplatform.avro.DeviceInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.deviceId)) {
        this.deviceId = data().deepCopy(fields()[0].schema(), other.deviceId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.deviceType)) {
        this.deviceType = data().deepCopy(fields()[1].schema(), other.deviceType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.manufacturer)) {
        this.manufacturer = data().deepCopy(fields()[2].schema(), other.manufacturer);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.model)) {
        this.model = data().deepCopy(fields()[3].schema(), other.model);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.firmwareVersion)) {
        this.firmwareVersion = data().deepCopy(fields()[4].schema(), other.firmwareVersion);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.firstSeen)) {
        this.firstSeen = data().deepCopy(fields()[5].schema(), other.firstSeen);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.lastSeen)) {
        this.lastSeen = data().deepCopy(fields()[6].schema(), other.lastSeen);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.status)) {
        this.status = data().deepCopy(fields()[7].schema(), other.status);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'deviceId' field.
      * @return The value.
      */
    public java.lang.String getDeviceId() {
      return deviceId;
    }


    /**
      * Sets the value of the 'deviceId' field.
      * @param value The value of 'deviceId'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder setDeviceId(java.lang.String value) {
      validate(fields()[0], value);
      this.deviceId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceId' field has been set.
      * @return True if the 'deviceId' field has been set, false otherwise.
      */
    public boolean hasDeviceId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deviceId' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder clearDeviceId() {
      deviceId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviceType' field.
      * @return The value.
      */
    public java.lang.String getDeviceType() {
      return deviceType;
    }


    /**
      * Sets the value of the 'deviceType' field.
      * @param value The value of 'deviceType'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder setDeviceType(java.lang.String value) {
      validate(fields()[1], value);
      this.deviceType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceType' field has been set.
      * @return True if the 'deviceType' field has been set, false otherwise.
      */
    public boolean hasDeviceType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'deviceType' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder clearDeviceType() {
      deviceType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'manufacturer' field.
      * @return The value.
      */
    public java.lang.String getManufacturer() {
      return manufacturer;
    }


    /**
      * Sets the value of the 'manufacturer' field.
      * @param value The value of 'manufacturer'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder setManufacturer(java.lang.String value) {
      validate(fields()[2], value);
      this.manufacturer = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'manufacturer' field has been set.
      * @return True if the 'manufacturer' field has been set, false otherwise.
      */
    public boolean hasManufacturer() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'manufacturer' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder clearManufacturer() {
      manufacturer = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'model' field.
      * @return The value.
      */
    public java.lang.String getModel() {
      return model;
    }


    /**
      * Sets the value of the 'model' field.
      * @param value The value of 'model'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder setModel(java.lang.String value) {
      validate(fields()[3], value);
      this.model = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'model' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder clearModel() {
      model = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'firmwareVersion' field.
      * @return The value.
      */
    public java.lang.String getFirmwareVersion() {
      return firmwareVersion;
    }


    /**
      * Sets the value of the 'firmwareVersion' field.
      * @param value The value of 'firmwareVersion'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder setFirmwareVersion(java.lang.String value) {
      validate(fields()[4], value);
      this.firmwareVersion = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'firmwareVersion' field has been set.
      * @return True if the 'firmwareVersion' field has been set, false otherwise.
      */
    public boolean hasFirmwareVersion() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'firmwareVersion' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder clearFirmwareVersion() {
      firmwareVersion = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstSeen' field.
      * @return The value.
      */
    public long getFirstSeen() {
      return firstSeen;
    }


    /**
      * Sets the value of the 'firstSeen' field.
      * @param value The value of 'firstSeen'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder setFirstSeen(long value) {
      validate(fields()[5], value);
      this.firstSeen = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'firstSeen' field has been set.
      * @return True if the 'firstSeen' field has been set, false otherwise.
      */
    public boolean hasFirstSeen() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'firstSeen' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder clearFirstSeen() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastSeen' field.
      * @return The value.
      */
    public long getLastSeen() {
      return lastSeen;
    }


    /**
      * Sets the value of the 'lastSeen' field.
      * @param value The value of 'lastSeen'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder setLastSeen(long value) {
      validate(fields()[6], value);
      this.lastSeen = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'lastSeen' field has been set.
      * @return True if the 'lastSeen' field has been set, false otherwise.
      */
    public boolean hasLastSeen() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'lastSeen' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder clearLastSeen() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.String getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder setStatus(java.lang.String value) {
      validate(fields()[7], value);
      this.status = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.github.alexkiyanov.iotplatform.avro.DeviceInfo.Builder clearStatus() {
      status = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeviceInfo build() {
      try {
        DeviceInfo record = new DeviceInfo();
        record.deviceId = fieldSetFlags()[0] ? this.deviceId : (java.lang.String) defaultValue(fields()[0]);
        record.deviceType = fieldSetFlags()[1] ? this.deviceType : (java.lang.String) defaultValue(fields()[1]);
        record.manufacturer = fieldSetFlags()[2] ? this.manufacturer : (java.lang.String) defaultValue(fields()[2]);
        record.model = fieldSetFlags()[3] ? this.model : (java.lang.String) defaultValue(fields()[3]);
        record.firmwareVersion = fieldSetFlags()[4] ? this.firmwareVersion : (java.lang.String) defaultValue(fields()[4]);
        record.firstSeen = fieldSetFlags()[5] ? this.firstSeen : (java.lang.Long) defaultValue(fields()[5]);
        record.lastSeen = fieldSetFlags()[6] ? this.lastSeen : (java.lang.Long) defaultValue(fields()[6]);
        record.status = fieldSetFlags()[7] ? this.status : (java.lang.String) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeviceInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeviceInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeviceInfo>
    READER$ = (org.apache.avro.io.DatumReader<DeviceInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.deviceId);

    out.writeString(this.deviceType);

    out.writeString(this.manufacturer);

    out.writeString(this.model);

    out.writeString(this.firmwareVersion);

    out.writeLong(this.firstSeen);

    out.writeLong(this.lastSeen);

    out.writeString(this.status);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.deviceId = in.readString();

      this.deviceType = in.readString();

      this.manufacturer = in.readString();

      this.model = in.readString();

      this.firmwareVersion = in.readString();

      this.firstSeen = in.readLong();

      this.lastSeen = in.readLong();

      this.status = in.readString();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.deviceId = in.readString();
          break;

        case 1:
          this.deviceType = in.readString();
          break;

        case 2:
          this.manufacturer = in.readString();
          break;

        case 3:
          this.model = in.readString();
          break;

        case 4:
          this.firmwareVersion = in.readString();
          break;

        case 5:
          this.firstSeen = in.readLong();
          break;

        case 6:
          this.lastSeen = in.readLong();
          break;

        case 7:
          this.status = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










